name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
    steps:
#      - name: Wait for previous workflows
#        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
#        uses: softprops/turnstyle@v1
#        with:
#          poll-interval-seconds: 10
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out files
        uses: actions/checkout@v2.5.0
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Generate project files
        run: tools/premake5 vs2022 --ci-build

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/boiii.sln

      - name: Upload ${{matrix.configuration}} bundle
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{matrix.configuration}} Bundle
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii.exe
            build/bin/x64/${{matrix.configuration}}/boiii.pdb

      - name: Upload ${{matrix.configuration}} binary
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{matrix.configuration}} Binary
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii.exe

      - name: Upload version
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Version
          path: |
            build/version.txt
